version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: bank_transactions_etl
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5438:5432
  adminer:
    image: adminer
    container_name: adminer_container_bank_transactions_etl
    restart: always
    ports:
      - 8082:8080
volumes:
  example_db:

# changed adminer container port from 8081 to 8082 as 8080 and 80801 are in use
# changed postgres container port from 5432 to 5438 as 5432 was already in use